//
// AddObjectResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AddObjectResult: Codable {

    public var objectsInfo: [ARObject]?
    public var status: AddObjectStatus

    public init(objectsInfo: [ARObject]? = nil, status: AddObjectStatus) {
        self.objectsInfo = objectsInfo
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case objectsInfo = "objects_info"
        case status
    }

}

