//
// AugmentedCity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Information about the augmented city. Includes name, country and geometry of the city. */
public struct AugmentedCity: Codable {

    /** Numeric identifier of the city */
    public var cityId: Int
    /** Name of the city */
    public var city: String
    /** Name of the country where the city is located */
    public var country: String
    public var description: AugmentedCityDescription

    public init(cityId: Int, city: String, country: String, description: AugmentedCityDescription) {
        self.cityId = cityId
        self.city = city
        self.country = country
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case cityId = "city_id"
        case city
        case country
        case description
    }

}

