//
// AugmentedCityDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Additional city data */
public struct AugmentedCityDescription: Codable {

    public var circle: AugmentedCityDescriptionCircle

    public init(circle: AugmentedCityDescriptionCircle) {
        self.circle = circle
    }

}

