//
// AugmentedCityDescriptionCircle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** City center and radius */
public struct AugmentedCityDescriptionCircle: Codable {

    public var center: GeoPoint
    /** City radius in meters */
    public var radius: Float

    public init(center: GeoPoint, radius: Float) {
        self.center = center
        self.radius = radius
    }

}

