//
// Camera.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Camera: Codable {

    public var pose: Pose

    public init(pose: Pose) {
        self.pose = pose
    }

}

