//
// GeoPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Single geo position geometry type */
public struct GeoPoint: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case point = "Point"
    }
    public var type: ModelType
    /** Geo position in 3D space. A position is an array of numbers. There MUST be two or three elements. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Altitude or elevation MAY be included as an optional third element. */
    public var coordinates: [Double]

    public init(type: ModelType, coordinates: [Double]) {
        self.type = type
        self.coordinates = coordinates
    }

}

