//
// ImageDescriptionGps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ImageDescriptionGps: Codable {

    public var latitude: Float
    public var longitude: Float
    public var altitude: Float?
    public var hdop: Float?

    public init(latitude: Float, longitude: Float, altitude: Float? = nil, hdop: Float? = nil) {
        self.latitude = latitude
        self.longitude = longitude
        self.altitude = altitude
        self.hdop = hdop
    }

}

