//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject: Codable {

    public var description: ImageDescription
    /** A JPEG-encoded image */
    public var image: URL

    public init(description: ImageDescription, image: URL) {
        self.description = description
        self.image = image
    }

}

