//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject: Codable {

    /** A JPEG-encoded image, must include GPS data in EXIF tags */
    public var image: URL?

    public init(image: URL? = nil) {
        self.image = image
    }

}

