//
// ObjectWithPose.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ObjectWithPose: Codable {

    public var reconstructionId: Int
    public var pose: Pose
    public var frame: [Vector3d]?
    public var description: ObjectWithPoseDescription

    public init(reconstructionId: Int, pose: Pose, frame: [Vector3d]? = nil, description: ObjectWithPoseDescription) {
        self.reconstructionId = reconstructionId
        self.pose = pose
        self.frame = frame
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case reconstructionId = "reconstruction_id"
        case pose
        case frame
        case description
    }

}

