//
// ObjectWithPoseDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ObjectWithPoseDescription: Codable {

    public var sticker: StickerData

    public init(sticker: StickerData) {
        self.sticker = sticker
    }

}

