//
// PlaceholderNode3d.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PlaceholderNode3d: Codable {

    public var placeholderId: String
    public var pose: Pose
    public var frame: [Vector3d]?

    public init(placeholderId: String, pose: Pose, frame: [Vector3d]? = nil) {
        self.placeholderId = placeholderId
        self.pose = pose
        self.frame = frame
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case placeholderId = "placeholder_id"
        case pose
        case frame
    }

}

