//
// PlaceholderImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Marked image */
public struct PlaceholderImage: Codable {

    public var projections: [ImageProjections]

    public init(projections: [ImageProjections]) {
        self.projections = projections
    }

}

