//
// PrepareResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PrepareResult: Codable {

    public var status: PrepareStatus

    public init(status: PrepareStatus) {
        self.status = status
    }

}

