//
// Quaternion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Quaternion: Codable {

    public var w: Float
    public var x: Float
    public var y: Float
    public var z: Float

    public init(w: Float, x: Float, y: Float, z: Float) {
        self.w = w
        self.x = x
        self.y = y
        self.z = z
    }

}

