//
// ReconstructionStage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** | Stage  |  Description  |   | -- | -- |   | UPLOAD | Wait images upload |   | IN_QUEUE | Wait for processing |   | IN_PROCESS | Reconstruction in process |   | DONE | Processing is finished |   */
public enum ReconstructionStage: String, Codable, CaseIterable {
    case upload = "UPLOAD"
    case inQueue = "IN_QUEUE"
    case inProcess = "IN_PROCESS"
    case done = "DONE"
}
