//
// ReconstructedCityGps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReconstructedCityGps: Codable {

    public var latitude: Float
    public var longitude: Float
    public var radius: Float

    public init(latitude: Float, longitude: Float, radius: Float) {
        self.latitude = latitude
        self.longitude = longitude
        self.radius = radius
    }

}

