//
// ReconstructionTaskStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Series reconstruction task process info */
public struct ReconstructionTaskStatus: Codable {

    /** Series task id */
    public var taskId: UUID
    public var stage: ReconstructionStage
    /** List of uploaded images filenames */
    public var images: [String]?

    public init(taskId: UUID, stage: ReconstructionStage, images: [String]? = nil) {
        self.taskId = taskId
        self.stage = stage
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case taskId = "task_id"
        case stage
        case images
    }

}

