//
// ScanDaytime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** | Time of day  |  Description  |   | -- | -- |   | DAY |    |   | EVENING |  |   | NIGHT |  |   */
public enum ScanDaytime: String, Codable, CaseIterable {
    case day = "DAY"
    case evening = "EVENING"
    case night = "NIGHT"
}
