//
// ScanSeriesDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ScanSeriesDescription: Codable {

    /** Application name */
    public var client: String
    public var daytime: ScanDaytime
    /** Phone or camera model */
    public var device: String
    /** Location name */
    public var name: String
    public var passages: [ScanPassage]
    /** User login or id */
    public var user: String

    public init(client: String, daytime: ScanDaytime, device: String, name: String, passages: [ScanPassage], user: String) {
        self.client = client
        self.daytime = daytime
        self.device = device
        self.name = name
        self.passages = passages
        self.user = user
    }

}

