//
// ScanStyle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** | Scan style  |  Description  |   | -- | -- |   | LINEAR_AUTO |  |   | LINEAR_MANUAL |  |   | CIRCULAR_AUTO |  |   | CIRCULAR_MANUAL |  |   */
public enum ScanStyle: String, Codable, CaseIterable {
    case linearAuto = "LINEAR_AUTO"
    case linearManual = "LINEAR_MANUAL"
    case circularAuto = "CIRCULAR_AUTO"
    case circularManual = "CIRCULAR_MANUAL"
}
