//
// ScanFrame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ScanFrame: Codable {

    /** Unique image filename */
    public var filename: String
    public var camera: Camera?

    public init(filename: String, camera: Camera? = nil) {
        self.filename = filename
        self.camera = camera
    }

}

