//
// Surface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Surface: Codable {

    public var pose: Pose
    public var frame: [[Float]] //Vector2D

    public init(pose: Pose, frame: [[Float]]) {
        self.pose = pose
        self.frame = frame
    }

}

