//
// Vector3d.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Vector3d: Codable {

    public var x: Float
    public var y: Float
    public var z: Float

    public init(x: Float, y: Float, z: Float) {
        self.x = x
        self.y = y
        self.z = z
    }

}

