//
// Vector2i.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Vector2i: Codable {

    public var x: Int
    public var y: Int

    public init(x: Int, y: Int) {
        self.x = x
        self.y = y
    }

}

