//
// Vector2d.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Vector2d: Codable {

    public var x: Float
    public var y: Float

    public init(x: Float, y: Float) {
        self.x = x
        self.y = y
    }

}

